### ISSUE TITLE
CT Cannot set properties of undefined (setting 'fill')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-builder#120] opened 2022-04-12 14:45 UTC
```
area-builder : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at XM.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1595724)
at mO.updateYouEnteredWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1610407)
at mO.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1608468)
at mO.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1606083)
at ot.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:42435)
at ut._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:80882)
at ut.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:80258)
at Sk.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1474606)
at Sk.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1474024)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733322888%7D&fuzz&memoryLimit=1000:886:1602212)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at XM.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1595724)
at mO.updateYouEnteredWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1610407)
at mO.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1608468)
at mO.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1606083)
at ot.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:42435)
at ut._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:80882)
at ut.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:80258)
at Sk.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1474606)
at Sk.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1474024)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/build/phet/area-builder_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754425824%7D&fuzz&memoryLimit=1000:886:1602212)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649740160122%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouEnteredWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouEnteredWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:613:27)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:530:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754903600%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouBuiltWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouBuiltWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:604:25)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:521:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649751949883%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouEnteredWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouEnteredWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:613:27)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:530:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649736818797%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouEnteredWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouEnteredWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:613:27)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:530:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649754016386%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouEnteredWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouEnteredWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:613:27)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:530:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649733305601%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouBuiltWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouBuiltWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:604:25)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:521:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM

----------------------------------

area-builder : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/area-builder/area-builder_en.html?continuousTest=%7B%22test%22%3A%5B%22area-builder%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649757262974%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at YouBuiltWindow.setColorBasedOnAnswerCorrectness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/FeedbackWindow.js:69:26)
at AreaBuilderGameView.updateYouBuiltWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:604:25)
at AreaBuilderGameView.handleShowingIncorrectAnswerFeedbackMoveOnState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:521:12)
at AreaBuilderGameView.handleGameStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:411:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at QuizGameModel.handleProposedAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:188:32)
at QuizGameModel.checkAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/model/QuizGameModel.js:157:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/area-builder/js/game/view/AreaBuilderGameView.js:223:19)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM
```

**Comment by jbphet** [comment] 2022-04-13 23:11
This was caused by the port of `Panel.js` to `Panel.ts`.  The background was made private and renamed to `_background`, and one of the classes in area-builder was setting it.  It now uses the `setFill` method and works fine.  Closing.

**Closed by jbphet** 2022-04-13 23:11 UTC
Labels: type:automated-testing
