### ISSUE TITLE
Animations slow on iPad

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-builder#69] opened 2014-09-30 18:32 UTC
On 1.0.0-rc.4, certain block animations can be a bit slow.
1. The fading out of blocks when pressing the erase button is slow when large amounts of blocks are erased at once.
2. The animation during the game levels that show a correct solution after "A Solution" is pressed are slow, especially the larger and more complex ones in level 6.
3. The flying animation of blocks going across the screen when "flinging" many blocks out of the bucket quickly slows down.
Tested on iPad 2 (iOS 7 & 8) and iPad 3 (iOS8)

**Comment by jbphet** [comment] 2016-05-03 23:26
I've added a query parameter - ```prefillBoards``` - to make this easier to test.  It causes all of the boards in the explore screen to be initially filled so that clearing can be easily tested.

**Comment by jbphet** [comment] 2016-05-04 20:21
I added code to turn off perimeter and outline updates while adding a solution to the board.  This improved performance for solution animations on Chrome when measured using the profiling tools by about 44%, and when comparing frame rates on the an iPad 2 running iOS 8.4.1 (the device named "Lave") I saw frame rate improvements of 20-40%.  This should address the 2nd item in the description.

**Comment by jbphet** [comment] 2016-05-04 21:00
I tried putting layer splits in a few strategic places to try to improve fade rates, but these made no improvement that I could see or measure with the profiler, so I backed them out.

**Comment by jbphet** [comment] 2016-05-04 21:04
I also tested this on an iPad 2 running iOS 9.3.2 (the PhET iPad named "Tycho") and in my opinion, performance of all items noted in the issue is quite acceptable.  I think this is as much as I will try to do for the 1.1 version of this sim.

**Comment by phet-steele** [comment] 2016-05-12 15:31
> I think this is as much as I will try to do for the 1.1 version of this sim.

@jbphet agreed. Up to you to close or keep open for future optimization (since it isn't perfect yet).

**Comment by jbphet** [comment] 2016-05-12 16:09
Closing.

**Closed by jbphet** 2016-05-12 16:09 UTC
